### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by wssgcg1213** [Red-UI/notes#2]
- [x] packer initial
- [x] packer dev
- [x] packer build
- [x] packer 脚手架
- [x] project-example
- [x] component-example
- [x] 制定规范
- [ ] 文档站点

**Comment by wssgcg1213** [comment]
+ packer 支持自动安装缺失的模块

**Comment by wssgcg1213** [comment]
脚手架 DONE

red init

**Comment by wssgcg1213** [comment]
- [x] dev 切换到 memory-fs

**Comment by wssgcg1213** [comment]
- [ ] cssnano、uglify 参数调优
- [ ] dev 模式下 sourcemap

**Comment by wssgcg1213** [comment]
- [ ] node/cnpm 内置

**Comment by wssgcg1213** [comment]
- [ ] generator 增加 .gitignore

**Comment by wssgcg1213** [comment]
- [ ] packer 版本检测

**Comment by wssgcg1213** [comment]
- [ ] + Universal fe project （一般项目）
